Repository USB-CI3715/nodebb-usb-24-geektech, pull requests merged in 2024-11, with the labels that each got.

#35 Implementación de Roles de Usuario en el backend y Asignación Automática de Grupos con Restricciones de Acceso
  install/data/rols.json
  install/package.json
  src/api/users.js
  src/controllers/authentication.js
  src/controllers/user.js
  src/dummy.js
  src/routes/api.js
  src/socket.io/user.js
  src/upgrades/3.8.5/professors_groups.js
  src/upgrades/3.8.5/students_group.js
  src/user/create.js
  src/user/data.js
Labels: enhancement

#40 Conexion de front y back para el listado de urgencias
  nodebb-plugin-new/templates/partials/topic/post.tpl
  public/src/app.js
Labels: enhancement

#41 Creación los grupos para los roles estudiantes y profesores
  src/controllers/authentication.js
Labels: enhancement

#42 Actualizar selección de urgencia para cargar dinámicamente las opciones
  nodebb-plugin-new/templates/partials/topic/post.tpl
  public/src/app.js
Labels: enhancement

#44 Agregar seguimiento del estado de respuesta para posts
  src/api/posts.js
  src/controllers/write/posts.js
  src/posts/create.js
  src/posts/data.js
  src/posts/edit.js
  src/routes/write/posts.js
Labels: enhancement

#45 Agregar Endpoint para la obtencion de Post bassados en su urgencia y si fueron contestados o no
  nodebb-plugin-new/templates/partials/topic/post.tpl
  public/src/app.js
  src/api/posts.js
  src/controllers/write/posts.js
  src/install.js
  src/posts/create.js
  src/posts/data.js
  src/posts/edit.js
  src/posts/index.js
  src/routes/write/posts.js
Labels: enhancement

#48 Limpieza de pruebas para validaciones de test
  nodebb-plugin-new/templates/partials/topic/post.tpl
  public/openapi/components/schemas/PostObject.yaml
  public/openapi/components/schemas/Urgency.yaml
  public/src/app.js
  src/user/create.js
  test/api.js
  test/controllers-admin.js
  test/flags.js
  test/posts.js
  test/posts/uploads.js
  test/topics.js
  test/topics/thumbs.js
Labels: bug

#49 Implementacion interfaz de preguntas
  nodebb-plugin-new/templates/partials/topic/post.tpl
Labels: enhancement

#50 Añadir pruebas para las nuevas funcionalidades implementadas
  test/posts.js
  test/user.js
Labels: planification

#51 se agrega el boton de Contestada o sin contestar para una pregunta
  nodebb-plugin-new/templates/partials/topic/post.tpl
Labels: enhancement
